### ISSUE TITLE
Build broken on AARCH64

### ISSUE THREAD

**Issue by elfringham** [openxla/xla#6406]
Since https://github.com/openxla/xla/commit/0bcb0edab3da365a3bf6631d2e711c96b20e150d the build for AARCH64 is broken.

```
ERROR: /home/linaro/src/xla/xla/pjrt/BUILD:746:11: Compiling xla/pjrt/transpose.cc failed: (Exit 1): gcc failed: error executing command (from target //xla/pjrt:transpose) /usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 95 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from xla/pjrt/transpose.cc:94:
./xla/pjrt/transpose_kernels.h: In static member function 'static void xla::TransposeMicroKernel<T, bs>::Apply(const char*, int64_t, char*, int64_t)':
./xla/pjrt/transpose_kernels.h:710:46: error: '__m128i' was not declared in this scope
  710 |       if constexpr (sizeof(T) * bs <= sizeof(__m128i)) {
      |                                              ^~~~~~~
./xla/pjrt/transpose_kernels.h: In instantiation of 'static void xla::Vec128RectangularTransposeMicroKernelImpl<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = short unsigned int; int bs = 16; int64_t = long int]':
./xla/pjrt/transpose_kernels.h:711:71:   required from 'static void xla::TransposeMicroKernel<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = short unsigned int; int bs = 16; int64_t = long int]'
xla/pjrt/transpose.cc:170:47:   required from 'void xla::MacroKernel(const char*, int64_t, int, char*, int64_t, int, void*) [with T = short unsigned int; int inner_bs = 16; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone; int64_t = long int]'
xla/pjrt/transpose.cc:410:64:   required from 'xla::TransposePlan::ExecuteTyped<short unsigned int, xla::TransposePlan::Transformation::kNone>::<lambda(auto:23)> [with auto:23 = std::integral_constant<int, 16>]'
xla/pjrt/transpose.cc:429:33:   required from 'void xla::TransposePlan::ExecuteTyped(const char*, char*, absl::lts_20230125::Span<const xla::TransposePlan::Node>) const [with T = short unsigned int; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone]'
xla/pjrt/transpose.cc:459:68:   required from here
./xla/pjrt/transpose_kernels.h:576:34: error: static assertion failed
  576 |     static_assert(kBytesInMatrix <= sizeof(Vec128) * last_transpose.size());
      |                   ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./xla/pjrt/transpose_kernels.h: In instantiation of 'static void xla::Vec128RectangularTransposeMicroKernelImpl<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = unsigned int; int bs = 8; int64_t = long int]':
./xla/pjrt/transpose_kernels.h:711:71:   required from 'static void xla::TransposeMicroKernel<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = unsigned int; int bs = 8; int64_t = long int]'
xla/pjrt/transpose.cc:170:47:   required from 'void xla::MacroKernel(const char*, int64_t, int, char*, int64_t, int, void*) [with T = unsigned int; int inner_bs = 8; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone; int64_t = long int]'
xla/pjrt/transpose.cc:410:64:   required from 'xla::TransposePlan::ExecuteTyped<unsigned int, xla::TransposePlan::Transformation::kNone>::<lambda(auto:23)> [with auto:23 = std::integral_constant<int, 8>]'
xla/pjrt/transpose.cc:426:33:   required from 'void xla::TransposePlan::ExecuteTyped(const char*, char*, absl::lts_20230125::Span<const xla::TransposePlan::Node>) const [with T = unsigned int; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone]'
xla/pjrt/transpose.cc:463:70:   required from here
./xla/pjrt/transpose_kernels.h:576:34: error: static assertion failed
./xla/pjrt/transpose_kernels.h: In instantiation of 'static void xla::Vec128RectangularTransposeMicroKernelImpl<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = unsigned int; int bs = 16; int64_t = long int]':
./xla/pjrt/transpose_kernels.h:711:71:   required from 'static void xla::TransposeMicroKernel<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = unsigned int; int bs = 16; int64_t = long int]'
xla/pjrt/transpose.cc:170:47:   required from 'void xla::MacroKernel(const char*, int64_t, int, char*, int64_t, int, void*) [with T = unsigned int; int inner_bs = 16; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone; int64_t = long int]'
xla/pjrt/transpose.cc:410:64:   required from 'xla::TransposePlan::ExecuteTyped<unsigned int, xla::TransposePlan::Transformation::kNone>::<lambda(auto:23)> [with auto:23 = std::integral_constant<int, 16>]'
xla/pjrt/transpose.cc:429:33:   required from 'void xla::TransposePlan::ExecuteTyped(const char*, char*, absl::lts_20230125::Span<const xla::TransposePlan::Node>) const [with T = unsigned int; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone]'
xla/pjrt/transpose.cc:463:70:   required from here
./xla/pjrt/transpose_kernels.h:576:34: error: static assertion failed
./xla/pjrt/transpose_kernels.h: In instantiation of 'static void xla::Vec128RectangularTransposeMicroKernelImpl<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = long unsigned int; int bs = 4; int64_t = long int]':
./xla/pjrt/transpose_kernels.h:711:71:   required from 'static void xla::TransposeMicroKernel<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = long unsigned int; int bs = 4; int64_t = long int]'
xla/pjrt/transpose.cc:170:47:   required from 'void xla::MacroKernel(const char*, int64_t, int, char*, int64_t, int, void*) [with T = long unsigned int; int inner_bs = 4; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone; int64_t = long int]'
xla/pjrt/transpose.cc:410:64:   required from 'xla::TransposePlan::ExecuteTyped<long unsigned int, xla::TransposePlan::Transformation::kNone>::<lambda(auto:23)> [with auto:23 = std::integral_constant<int, 4>]'
xla/pjrt/transpose.cc:423:33:   required from 'void xla::TransposePlan::ExecuteTyped(const char*, char*, absl::lts_20230125::Span<const xla::TransposePlan::Node>) const [with T = long unsigned int; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone]'
xla/pjrt/transpose.cc:470:68:   required from here
./xla/pjrt/transpose_kernels.h:576:34: error: static assertion failed
./xla/pjrt/transpose_kernels.h: In instantiation of 'static void xla::Vec128RectangularTransposeMicroKernelImpl<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = long unsigned int; int bs = 8; int64_t = long int]':
./xla/pjrt/transpose_kernels.h:711:71:   required from 'static void xla::TransposeMicroKernel<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = long unsigned int; int bs = 8; int64_t = long int]'
xla/pjrt/transpose.cc:170:47:   required from 'void xla::MacroKernel(const char*, int64_t, int, char*, int64_t, int, void*) [with T = long unsigned int; int inner_bs = 8; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone; int64_t = long int]'
xla/pjrt/transpose.cc:410:64:   required from 'xla::TransposePlan::ExecuteTyped<long unsigned int, xla::TransposePlan::Transformation::kNone>::<lambda(auto:23)> [with auto:23 = std::integral_constant<int, 8>]'
xla/pjrt/transpose.cc:426:33:   required from 'void xla::TransposePlan::ExecuteTyped(const char*, char*, absl::lts_20230125::Span<const xla::TransposePlan::Node>) const [with T = long unsigned int; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone]'
xla/pjrt/transpose.cc:470:68:   required from here
./xla/pjrt/transpose_kernels.h:576:34: error: static assertion failed
./xla/pjrt/transpose_kernels.h: In instantiation of 'static void xla::Vec128RectangularTransposeMicroKernelImpl<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = long unsigned int; int bs = 16; int64_t = long int]':
./xla/pjrt/transpose_kernels.h:711:71:   required from 'static void xla::TransposeMicroKernel<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = long unsigned int; int bs = 16; int64_t = long int]'
xla/pjrt/transpose.cc:170:47:   required from 'void xla::MacroKernel(const char*, int64_t, int, char*, int64_t, int, void*) [with T = long unsigned int; int inner_bs = 16; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone; int64_t = long int]'
xla/pjrt/transpose.cc:410:64:   required from 'xla::TransposePlan::ExecuteTyped<long unsigned int, xla::TransposePlan::Transformation::kNone>::<lambda(auto:23)> [with auto:23 = std::integral_constant<int, 16>]'
xla/pjrt/transpose.cc:429:33:   required from 'void xla::TransposePlan::ExecuteTyped(const char*, char*, absl::lts_20230125::Span<const xla::TransposePlan::Node>) const [with T = long unsigned int; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone]'
xla/pjrt/transpose.cc:470:68:   required from here
./xla/pjrt/transpose_kernels.h:576:34: error: static assertion failed
./xla/pjrt/transpose_kernels.h: In instantiation of 'static void xla::Vec128RectangularTransposeMicroKernelImpl<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = xla::uint128; int bs = 2; int64_t = long int]':
./xla/pjrt/transpose_kernels.h:711:71:   required from 'static void xla::TransposeMicroKernel<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = xla::uint128; int bs = 2; int64_t = long int]'
xla/pjrt/transpose.cc:170:47:   required from 'void xla::MacroKernel(const char*, int64_t, int, char*, int64_t, int, void*) [with T = xla::uint128; int inner_bs = 2; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone; int64_t = long int]'
xla/pjrt/transpose.cc:410:64:   required from 'xla::TransposePlan::ExecuteTyped<xla::uint128, xla::TransposePlan::Transformation::kNone>::<lambda(auto:23)> [with auto:23 = std::integral_constant<int, 2>]'
xla/pjrt/transpose.cc:420:33:   required from 'void xla::TransposePlan::ExecuteTyped(const char*, char*, absl::lts_20230125::Span<const xla::TransposePlan::Node>) const [with T = xla::uint128; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone]'
xla/pjrt/transpose.cc:473:67:   required from here
./xla/pjrt/transpose_kernels.h:576:34: error: static assertion failed
./xla/pjrt/transpose_kernels.h: In instantiation of 'static void xla::Vec128RectangularTransposeMicroKernelImpl<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = xla::uint128; int bs = 4; int64_t = long int]':
./xla/pjrt/transpose_kernels.h:711:71:   required from 'static void xla::TransposeMicroKernel<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = xla::uint128; int bs = 4; int64_t = long int]'
xla/pjrt/transpose.cc:170:47:   required from 'void xla::MacroKernel(const char*, int64_t, int, char*, int64_t, int, void*) [with T = xla::uint128; int inner_bs = 4; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone; int64_t = long int]'
xla/pjrt/transpose.cc:410:64:   required from 'xla::TransposePlan::ExecuteTyped<xla::uint128, xla::TransposePlan::Transformation::kNone>::<lambda(auto:23)> [with auto:23 = std::integral_constant<int, 4>]'
xla/pjrt/transpose.cc:423:33:   required from 'void xla::TransposePlan::ExecuteTyped(const char*, char*, absl::lts_20230125::Span<const xla::TransposePlan::Node>) const [with T = xla::uint128; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone]'
xla/pjrt/transpose.cc:473:67:   required from here
./xla/pjrt/transpose_kernels.h:576:34: error: static assertion failed
./xla/pjrt/transpose_kernels.h: In instantiation of 'static void xla::Vec128RectangularTransposeMicroKernelImpl<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = xla::uint128; int bs = 8; int64_t = long int]':
./xla/pjrt/transpose_kernels.h:711:71:   required from 'static void xla::TransposeMicroKernel<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = xla::uint128; int bs = 8; int64_t = long int]'
xla/pjrt/transpose.cc:170:47:   required from 'void xla::MacroKernel(const char*, int64_t, int, char*, int64_t, int, void*) [with T = xla::uint128; int inner_bs = 8; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone; int64_t = long int]'
xla/pjrt/transpose.cc:410:64:   required from 'xla::TransposePlan::ExecuteTyped<xla::uint128, xla::TransposePlan::Transformation::kNone>::<lambda(auto:23)> [with auto:23 = std::integral_constant<int, 8>]'
xla/pjrt/transpose.cc:426:33:   required from 'void xla::TransposePlan::ExecuteTyped(const char*, char*, absl::lts_20230125::Span<const xla::TransposePlan::Node>) const [with T = xla::uint128; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone]'
xla/pjrt/transpose.cc:473:67:   required from here
./xla/pjrt/transpose_kernels.h:576:34: error: static assertion failed
./xla/pjrt/transpose_kernels.h: In instantiation of 'static void xla::Vec128RectangularTransposeMicroKernelImpl<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = xla::uint128; int bs = 16; int64_t = long int]':
./xla/pjrt/transpose_kernels.h:711:71:   required from 'static void xla::TransposeMicroKernel<T, bs>::Apply(const char*, int64_t, char*, int64_t) [with T = xla::uint128; int bs = 16; int64_t = long int]'
xla/pjrt/transpose.cc:170:47:   required from 'void xla::MacroKernel(const char*, int64_t, int, char*, int64_t, int, void*) [with T = xla::uint128; int inner_bs = 16; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone; int64_t = long int]'
xla/pjrt/transpose.cc:410:64:   required from 'xla::TransposePlan::ExecuteTyped<xla::uint128, xla::TransposePlan::Transformation::kNone>::<lambda(auto:23)> [with auto:23 = std::integral_constant<int, 16>]'
xla/pjrt/transpose.cc:429:33:   required from 'void xla::TransposePlan::ExecuteTyped(const char*, char*, absl::lts_20230125::Span<const xla::TransposePlan::Node>) const [with T = xla::uint128; xla::TransposePlan::Transformation transformation = xla::TransposePlan::Transformation::kNone]'
xla/pjrt/transpose.cc:473:67:   required from here
./xla/pjrt/transpose_kernels.h:576:34: error: static assertion failed
xla/pjrt/transpose.cc: In function 'void xla::ConvertF64ToEf57(const double*, float*, int)':
xla/pjrt/transpose.cc:139:51: note: parameter passing for argument of type 'std::pair<float, float>' when C++17 is enabled changed to match C++14 in GCC 10.1
  139 |     std::tie(output[0], output[1]) = SplitF64ToF32(*input);
      |                                      ~~~~~~~~~~~~~^~~~~~~~
INFO: Elapsed time: 10.924s, Critical Path: 9.83s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
(py39_venv) linaro@rack4-thx2-01:~/src/xla$ git bisect bad
0bcb0edab3da365a3bf6631d2e711c96b20e150d is the first bad commit
commit 0bcb0edab3da365a3bf6631d2e711c96b20e150d
Author: David Majnemer <majnemer@google.com>
Date:   Mon Oct 16 16:14:52 2023 -0700

    [PJRT] Fold all the specializations of TransposeMicroKernel away
    
    We can rely on some `if constexpr` logic to determine which implementation to use for a given block size and element width.
    
    PiperOrigin-RevId: 573959077

 xla/pjrt/transpose_kernels.h | 225 +++++++------------------------------------
 1 file changed, 34 insertions(+), 191 deletions(-)
```

**Comment by elfringham** [comment]
Never mind, I see it has been reverted now. Sorry for the noise.
