### ISSUE TITLE
Failure in building on Ubuntu 20.04: undeclared SO_ZEROCOPY

### ISSUE THREAD

**Issue by pearu** [openxla/xla#22083]
Building JAX on Ubuntu 20.04.6 LTS (Linux 5.4.0-171-generic) leads to the following compilation error:
```
external/xla/xla/python/transfer/socket-server.cc:366:44: error: use of undeclared identifier 'SO_ZEROCOPY'
  366 |   CHECK_GE(setsockopt(send_fd, SOL_SOCKET, SO_ZEROCOPY, &value, sizeof(value)),
```

`SO_ZEROCOPY` dependency to XLA was introduced in https://github.com/openxla/xla/pull/21496.

As a temporary workaround, applying the following patch to XLA fixes the build failure:

<details>

```
diff --git a/xla/python/transfer/event_loop.cc b/xla/python/transfer/event_loop.cc
index 029d9c0b8c..9832b1cb29 100644
--- a/xla/python/transfer/event_loop.cc
+++ b/xla/python/transfer/event_loop.cc
@@ -40,6 +40,10 @@ limitations under the License.
 #include "absl/synchronization/mutex.h"
 #include "tsl/platform/env.h"
 
+#ifndef SO_ZEROCOPY
+#define SO_ZEROCOPY    60
+#endif
+
 namespace aux {
 
 class PollEventLoopImpl : public PollEventLoop {
diff --git a/xla/python/transfer/socket-server.cc b/xla/python/transfer/socket-server.cc
index 69c8c027df..f8c51ea8b8 100644
--- a/xla/python/transfer/socket-server.cc
+++ b/xla/python/transfer/socket-server.cc
@@ -35,6 +35,10 @@ limitations under the License.
 #include "xla/python/transfer/transfer_socket.pb.h"
 #include "xla/tsl/concurrency/ref_count.h"
 
+#ifndef SO_ZEROCOPY
+#define SO_ZEROCOPY    60
+#endif
+
 namespace aux {
 
 class SocketServer::SocketNetworkState : public PollEventLoop::Handler {
diff --git a/xla/python/transfer/socket_bulk_transport.cc b/xla/python/transfer/socket_bulk_transport.cc
index 7b61c81c0e..7d41223426 100644
--- a/xla/python/transfer/socket_bulk_transport.cc
+++ b/xla/python/transfer/socket_bulk_transport.cc
@@ -42,6 +42,15 @@ limitations under the License.
 #include "xla/python/transfer/streaming.h"
 #include "xla/tsl/platform/env.h"
 
+#ifndef SO_ZEROCOPY
+#define SO_ZEROCOPY    60
+#endif
+
+#ifndef SO_EE_ORIGIN_ZEROCOPY
+#define SO_EE_ORIGIN_ZEROCOPY  5
+#endif
+
+
 namespace aux {
 
 ZeroCopySendAckTable::ZeroCopySendAckTable() {
```

</details>

zero-copy networking support was introduced in [2017](https://lwn.net/Articles/726917/) but the ubuntu linux kernel 5.4.0 dates from 2020, so the reason for undeclared `SO_ZEROCOPY` is not clear.

**Comment by akuegel** [comment]
@pschuh seems this was a commit from you?

**Comment by pearu** [comment]
This issue could be due to conda sysroot headers being too old, see similar issue https://github.com/pytorch/pytorch/issues/29093

**Comment by pearu** [comment]
This issue appears when using conda sysroot that is based on glibc 2.12 + kernel 2.6. Upgrading sysroot via
```sh
conda install sysroot_linux-64=2.17
```
is an alternative solution to this issue.
