### ISSUE TITLE
hlo_sharding_util_test fails to build with g++ 11.3.0

### ISSUE THREAD

**Issue by jakeh-gc** [openxla/xla#3849]
Changes in a781713 introduce this error:
```
xla/hlo/utils/hlo_sharding_util_test.cc:167:60: error: call of overloaded 'TileAssignment(<brace-enclosed initializer list>)' is ambiguous
  167 |   EXPECT_EQ(result.tile_assignment(), TileAssignment({4, 1}));
      |                                                            ^
In file included from ./xla/hlo/ir/hlo_sharding.h:34,
                 from ./xla/hlo/ir/hlo_instruction.h:48,
                 from ./xla/hlo/ir/hlo_computation.h:35,
                 from ./xla/hlo/utils/hlo_sharding_util.h:28,
                 from xla/hlo/utils/hlo_sharding_util_test.cc:16:
./xla/hlo/ir/tile_assignment.h:173:12: note: candidate: 'xla::TileAssignment::TileAssignment(absl::lts_20230125::Span<const long int>)'
  173 |   explicit TileAssignment(absl::Span<const int64_t> dims)
      |            ^~~~~~~~~~~~~~
./xla/hlo/ir/tile_assignment.h:172:12: note: candidate: 'xla::TileAssignment::TileAssignment(xla::IotaTileAssignment)'
  172 |   explicit TileAssignment(IotaTileAssignment iota) : iota_(std::move(iota)) {}
      |            ^~~~~~~~~~~~~~
In file included from external/com_google_googletest/googletest/include/gtest/gtest.h:67,
                 from external/com_google_googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:50,
                 from external/com_google_googletest/googlemock/include/gmock/gmock-actions.h:145,
                 from ./xla/test.h:42,
                 from xla/hlo/utils/hlo_sharding_util_test.cc:23:
xla/hlo/utils/hlo_sharding_util_test.cc: In member function 'virtual void xla::hlo_sharding_util::{anonymous}::HloShardingUtilTest_GetManualSubgroupSharding_ManualOnly_Test::TestBody()':
```
when compiling with 
```
$ g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
```

**Comment by cheshire** [comment]
There's a supported set of toolchains for XLA, I'm not sure whether this GCC version falls into it. Also @ddunl .

**Comment by jakeh-gc** [comment]
> There's a supported set of toolchains for XLA, I'm not sure whether this GCC version falls into it.

That's correct. The (possible incorrect?) documentation says `gcc-10` here:
https://github.com/openxla/xla/blob/a80fc98b46cd24488d15c6114e1d13216566a914/docs/build_from_source.md?plain=1#L46-L49
Since I'm seeing this issue on GCC 11.3, it seems reasonable to report and fix.

**Comment by jakeh-gc** [comment]
This has been reported and fixed on the TF repo, and copied across. https://github.com/tensorflow/tensorflow/issues/61068 https://github.com/tensorflow/tensorflow/pull/61081
