### PR TITLE
Fix ambiguous overload call in tests.

### LINKED ISSUE #3849: hlo_sharding_util_test fails to build with g++ 11.3.0
Changes in a781713 introduce this error:
```
xla/hlo/utils/hlo_sharding_util_test.cc:167:60: error: call of overloaded 'TileAssignment(<brace-enclosed initializer list>)' is ambiguous
  167 |   EXPECT_EQ(result.tile_assignment(), TileAssignment({4, 1}));
      |                                                            ^
In file included from ./xla/hlo/ir/hlo_sharding.h:34,
                 from ./xla/hlo/ir/hlo_instruction.h:48,
                 from ./xla/hlo/ir/hlo_computation.h:35,
                 from ./xla/hlo/utils/hlo_sharding_util.h:28,
                 from xla/hlo/utils/hlo_sharding_util_test.cc:16:
./xla/hlo/ir/tile_assignment.h:173:12: note: candidate: 'xla::TileAssignment::TileAssignment(absl::lts_20230125::Span<const long int>)'
  173 |   explicit TileAssignment(absl::Span<const int64_t> dims)
      |            ^~~~~~~~~~~~~~
./xla/hlo/ir/tile_assignment.h:172:12: note: candidate: 'xla::TileAssignment::TileAssignment(xla::IotaTileAssignment)'
  172 |   explicit TileAssignment(IotaTileAssignment iota) : iota_(std::move(iota)) {}
      |            ^~~~~~~~~~~~~~
In file included from external/com_google_googletest/googletest/include/gtest/gtest.h:67,
                 from external/com_google_googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:50,
                 from external/com_google_googletest/googlemock/include/gmock/gmock-actions.h:145,
                 from ./xla/test.h:42,
                 from xla/hlo/utils/hlo_sharding_util_test.cc:23:
xla/hlo/utils/hlo_sharding_util_test.cc: In member function 'virtual void xla::hlo_sharding_util::{anonymous}::HloShardingUtilTest_GetManualSubgroupSharding_ManualOnly_Test::TestBody()':
```
when compiling with 
```
$ g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
```

### PR DESCRIPTION
**Pull request by jakeh-gc**
Fixes #3849

### CODE REVIEW

**Review by ddunl — APPROVED** [review]

**Comment by ddunl** [comment]
Thanks for the PR! Should be merged soonish (within 24 hours)

**Comment by jakeh-gc** [comment]
Thanks for the review @ddunl.
I'm closing this because it has been fixed on the TF side of the fence in https://github.com/tensorflow/tensorflow/pull/61081
