### ISSUE TITLE
Build failure: `xla/experiments/sm_bandwidth_benchmark/sm_bw_kernels.cu.cc(86): error: zero-sized variable "buffer" is not allowed in device code`

### ISSUE THREAD

**Issue by joker-eph** [openxla/xla#3129]
Introduced in 76ebd4478293fc539421cc2ec9a452538769ad2d

**Comment by joker-eph** [comment]
The update to use a vector seems clearly buggy.
But even commenting out the faulty code, this fails during link:
```
sm_bw_test.cc:(.text._ZN11experiments9benchmark12_GLOBAL__N_132UseMaxNumberOfRegistersPerSmImplILi5EEclEv.isra.0+0x98): undefined reference to `cudaMemcpy'
/usr/bin/ld: sm_bw_test.cc:(.text._ZN11experiments9benchmark12_GLOBAL__N_132UseMaxNumberOfRegistersPerSmImplILi5EEclEv.isra.0+0x201): undefined reference to `cudaFree'
/usr/bin/ld: sm_bw_test.cc:(.text._ZN11experiments9benchmark12_GLOBAL__N_132UseMaxNumberOfRegistersPerSmImplILi5EEclEv.isra.0+0x212): undefined reference to `cudaFree'
/usr/bin/ld: bazel-out/k8-opt/bin/_solib_local/libxla_Sexperiments_Ssm_Ubandwidth_Ubenchmark_Slibsm_Ubw_Ukernels.so: undefined reference to `cudaLaunchKernel'
/usr/bin/ld: bazel-out/k8-opt/bin/_solib_local/libxla_Sexperiments_Ssm_Ubandwidth_Ubenchmark_Slibsm_Ubw_Ukernels.so: undefined reference to `__cudaRegisterFunction'
/usr/bin/ld: bazel-out/k8-opt/bin/_solib_local/libxla_Sexperiments_Ssm_Ubandwidth_Ubenchmark_Slibsm_Ubw_Ukernels.so: undefined reference to `__cudaRegisterFatBinaryEnd'
/usr/bin/ld: bazel-out/k8-opt/bin/_solib_local/libxla_Sexperiments_Ssm_Ubandwidth_Ubenchmark_Slibsm_Ubw_Ukernels.so: undefined reference to `__cudaUnregisterFatBinary'
/usr/bin/ld: bazel-out/k8-opt/bin/_solib_local/libxla_Sexperiments_Ssm_Ubandwidth_Ubenchmark_Slibsm_Ubw_Ukernels.so: undefined reference to `__cudaRegisterFatBinary'
/usr/bin/ld: bazel-out/k8-opt/bin/_solib_local/libxla_Sexperiments_Ssm_Ubandwidth_Ubenchmark_Slibsm_Ubw_Ukernels.so: undefined reference to `__cudaPopCallConfiguration'
/usr/bin/ld: bazel-out/k8-opt/bin/_solib_local/libxla_Sexperiments_Ssm_Ubandwidth_Ubenchmark_Slibsm_Ubw_Ukernels.so: undefined reference to `__cudaPushCallConfiguration'
```

Please try to build in OSS when fixing this (the official instructions to build are in the readme)

**Comment by cheshire** [comment]
The code was purely an experiment to gather some statistics, not sure if it's valuable to keep it check in and spend the maintenance cost on it. @gflegar maybe easier to remove it?

**Comment by gflegar** [comment]
Yeah, this was an oversight, and an easy fix (see referenced CL). I wouldn't remove it unless there's actually a significant maintenance burden. We'll still want to gather the same statistics on newer GPU generations, so I do find a set of microbenchmarks that we can keep around useful.

Not sure why this wasn't caught by our presubmits, the open source ones also passed, and I can't reproduce this with neither CUDA 11, nor CUDA 12 internally. Maybe our presubmits are also using clang to compile, and this fails only with nvcc?

I'll try an open source build before submitting this, but I can't at this moment, since our build seems broken by a missing LLVM dependency.

**Comment by joker-eph** [comment]
Thanks, that comment fixes the compile time issue, there is now a linker failure: https://gist.github.com/joker-eph/79244e0282e63fed7c4c2066b02f7da6

**Comment by gflegar** [comment]
I think the updated commit should fix the linker error. Though I couldn't do the final test because the zlib issue from yesterday is now broken once more (should hopefully be fixed soon, the right people are aware).

Note that if you try to actually run the `sw_bw_kernels_test`, it now reports that CUDA is a stub and fails. Didn't manage to figure out how to fix that one yet. But I assume you're not very interested in running this experiment, just unblocking your XLA build.

**Comment by joker-eph** [comment]
Well I just cherry-picked your fix on the same base as yesterday and I can confirm it builds successfully, thanks!
