### PR TITLE
[ROCm] Fix compilation errors in rocm_dnn

### PR DESCRIPTION
**Pull request by ekuznetsov139**
This fixes rocm_dnn after it got broken by the commit https://github.com/openxla/xla/commit/616486056afc4c97cc419d5cb8a033121c84e3d7.

It also corrects a small issue in ir_emitter_unnested.h (that header file needs to include rocm_config.h, otherwise some methods of IrEmitterUnnested will be missing their declarations).

### CODE REVIEW

File: xla/service/gpu/ir_emitter_unnested.h [hunk 1]
```diff
@@ -48,6 +48,11 @@ limitations under the License.
 #include "xla/status.h"
 #include "xla/statusor.h"
 
+#if TENSORFLOW_USE_ROCM
+// for TF_HIPBLASLT
+#include "rocm/rocm_config.h"
```
Comment (akuegel) [inline xla/service/gpu/ir_emitter_unnested.h:53]: Would this need a corresponding BUILD file change?

File: xla/stream_executor/rocm/rocm_dnn.h [hunk 2]
```diff
@@ -22,6 +22,7 @@ limitations under the License.
 #include "absl/synchronization/mutex.h"
 #include "absl/types/span.h"
 #include "rocm/include/miopen/miopen.h"
+#include "xla/stream_executor/device_memory_allocator.h"
```
Comment (akuegel) [inline xla/stream_executor/rocm/rocm_dnn.h:25]: I think this needs a corresponding BUILD file update

Comment (ekuznetsov139) [reply xla/stream_executor/rocm/rocm_dnn.h:25]: It builds as-is.

Comment (akuegel) [reply xla/stream_executor/rocm/rocm_dnn.h:25]: Not in a strict mode. With layering check enabled, for every header include you need to have a corresponding dependency to a target that has it listed in its hdrs section.

Comment (akuegel) [reply xla/stream_executor/rocm/rocm_dnn.h:25]: So the target you would need to depend on here is //xla/stream_executor:device_memory_allocator

File: xla/service/gpu/ir_emitter_unnested.h (hunk 1 above)
Comment (ekuznetsov139) [reply xla/service/gpu/ir_emitter_unnested.h:53]: it's an existing dependency via service/gpu/ir_emitter_unnested -> service/gpu/gpu_executable -> @local_config_rocm//rocm:rocm_headers

Comment (akuegel) [reply xla/service/gpu/ir_emitter_unnested.h:53]: Yes, but it is better not to rely on transitive dependencies. layering_check will complain about that.

Comment (ekuznetsov139) [reply xla/service/gpu/ir_emitter_unnested.h:53]: How do I reproduce that complaint? I'm running
```
bazel test --config=rocm  \
    --build_tag_filters=-no_oss,-oss_excluded,-oss_serial,gpu,-no_gpu,-no_rocm --test_tag_filters=-no_oss,-oss_excluded,-oss_serial,gpu,-no_gpu,-no_rocm --test_output=errors --features=layering_check \
    --flaky_test_attempts=3 --jobs=150 --run_under=//tools/ci_build/gpu_build:parallel_gpu_execute  \
    --keep_going --nocache_test_results   --test_env=TF_GPU_COUNT=8 --local_test_jobs=32 \
    --    //xla/... //build_tools/... -//xla/stream_executor/cuda/...
```

and I'm not getting any warnings about dependencies.

Comment (akuegel) [reply xla/service/gpu/ir_emitter_unnested.h:53]: It is possible that in open source, layering_check does not work so well. Since we don't build ROCM internally, it probably doesn't matter, but from an engineering standpoint it makes sense to have direct dependencies for header includes. Otherwise the path to the dependency can be broken if the dependency is removed from the other target. Thanks for adding the dependencies :)

**Review by akuegel — APPROVED** [review]
